### ISSUE TITLE
Stop commenting on wontfixed issues/pull requests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-bots#9]
The bot leaves a comment even when we close a PR with unmerged commits (wontfix). It's confusing, it should stop doing that.

**Comment by diox** [comment]
Also, if you remove one of those superfluous comments the bot will repost it. That's... not great.

**Comment by wagnerand** [comment]
Looks like the bot can't distinguish between PRs it didn't comment on yet and PRs where its comment got deleted.

**Comment by wagnerand** [comment]
I think that's what https://github.com/mozilla/addons-bots/blob/master/deploy_comment.py#L73 is supposed to do for pull requests?

**Comment by andymckay** [comment]
I would like to avoid having to make the bot keep a database of the things its commented on, currently all the tools here don't maintain their state so they are really easy to run. If you delete a comment from the bot, its no longer in the pull request.

If the patch to this issue works then we won't need to delete any comments.
